Damir mu
DenisTagaev/webchat pull request #11
Opened 2023-04-15 17:14 UTC by Damir-Mu

2023-04-15 17:52 UTC, DenisTagaev requested changes

2023-04-15 17:52 UTC, DenisTagaev commented on src/components/Chats/Chats.jsx
>              </div>
Check mobile view for the spans

2023-04-15 17:52 UTC, DenisTagaev commented on src/components/Navbar/Navbar.jsx
>            });
???

2023-04-15 17:52 UTC, DenisTagaev commented on src/components/context/AuthContext.js
>                  await updateDoc(doc(db, "users", user.uid), {
A lot of extra spaces, not really necessary, maybe you should check your formatter settings.

2023-04-15 17:52 UTC, DenisTagaev commented on src/pages/profile/AuthTab/AuthTab.jsx
>          }
Good job, much cleaner code!

2023-04-15 17:52 UTC, DenisTagaev commented on src/pages/profile/AuthTab/AuthTab.jsx
> +                        <button className="iconBtn" type="submit" disabled={formErrors.email || formErrors.password}>Log in<AiFillEdit /></button>
You sure about `formErrors.email`? Where are you setting this error?

2023-04-15 17:52 UTC, DenisTagaev commented on src/pages/profile/ProfileTab/ProfileTab.jsx
>          }
Commented

2023-04-15 17:53 UTC, Damir-Mu commented on src/pages/profile/AuthTab/AuthTab.jsx
>          }
Thank you, you are a mentor figure

2023-04-15 20:06 UTC, DenisTagaev requested changes

2023-04-15 20:06 UTC, DenisTagaev commented on src/pages/profile/ProfileTab/ProfileTab.jsx
>              });
data.profileDescription ? setDesc(data.profileDescription) : setDesc(formDesc);

2023-04-15 20:06 UTC, DenisTagaev commented on src/pages/profile/ProfileTab/ProfileTab.jsx
>      const [descriptionChangeAccess, setDescriptionChangeAccess] = useState(false);
useState({})

2023-04-16 01:49 UTC, DenisTagaev approved these changes

2023-04-16 01:49 UTC, merged